### ISSUE TITLE
不支持布尔类型的表达式

### ISSUE THREAD

**Issue by xinshoushangdao** [zqlovejyc/SQLBuilder.Core#2]
repository.FindList<Account>(m=>!m.IsDeleted&&m.IsDeleted==false).ToList();
!m.IsDeleted 和 m.IsDeleted==false 都会报错.
![image](https://user-images.githubusercontent.com/27396291/71464120-87606880-27f3-11ea-9659-1b1a1d548555.png)

**Comment by zqlovejyc** [comment]
已修复此bug
