### ISSUE TITLE
数据库连接字符自动注入

### ISSUE THREAD

**Issue by liyang-love** [zqlovejyc/SQLBuilder.Core#4]
Repository能否根据传入的连接字符串类型(providerName="System.Data.OracleClient")自动判断注入的数据库类型实例,而不是每次IOC容器前先选择数据库类型进行注入

**Comment by zqlovejyc** [comment]
这个问题，暂时不支持，具体注入Ioc可以查看扩展方法AddSQLBuilder方法注释；
