### ISSUE TITLE
select 的时候会生成 select * from

### ISSUE THREAD

**Issue by liyang-love** [zqlovejyc/SQLBuilder.Core#5]
如题：select 实体的时候会生成select * from ，DBA会要求查询时必须使用字段名提高性能 如： select name,sex, from a

 代码里的这句： SqlBuilder.Select<UserInfo>()

另外 Oracle。 生成的会加 “” 但是Oracle面的双引号的意义是区分大小写，而实际属性字段都是首字母大写，会产生错误。

作者能否优化下。

**Comment by zqlovejyc** [comment]
第一个问题，需要指定要查询的列即可；第二个问题，现在默认设置了不启用格式化的配置，具体参照单元测试用例；
