### ISSUE TITLE
有没有方法可以记录sql执行耗时

### ISSUE THREAD

**Issue by liyang-love** [zqlovejyc/SQLBuilder.Core#6]
有没有方法可以记录sql执行耗时，如果没有的话作者大佬可以支持下么

**Comment by zqlovejyc** [comment]
> 有没有方法可以记录sql执行耗时，如果没有的话作者大佬可以支持下么

SQLBuilder.Core SkyWalking和SQLBuilder.Core ElasticApm这两个类库，就可以追踪sql执行耗时以及sql语句和参数；另外也可以自己实现DiagnosticSource也可以，具体可以参照SQLBuilder.Core.Console内Program相关代码即可。
