### ISSUE TITLE
Oracle批量插入clob类型的字段报错

### ISSUE THREAD

**Issue by liyang-love** [zqlovejyc/SQLBuilder.Core#7]
Oracle批量插入clob类型的字段报错

SqlBuilder
        .Insert<MsdBoxEntity>(() =>
            new[]
            {
                new UserInfo { Remark = "xxxxxxxxxxxxx", Sex = 2 },
                new UserInfo { Remark = "xxxxxxxxxxxxx", Sex = 2 }
            })

如上如果Remark是clob类型的，插入多条超长字符串时 或报错，但是实际oracle是支持clob的

**Comment by zqlovejyc** [comment]
> Oracle批量插入clob类型的字段报错
> 
> SqlBuilder .Insert(() => new[] { new UserInfo { Remark = "xxxxxxxxxxxxx", Sex = 2 }, new UserInfo { Remark = "xxxxxxxxxxxxx", Sex = 2 } })
> 
> 如上如果Remark是clob类型的，插入多条超长字符串时 或报错，但是实际oracle是支持clob的

这个 你单独使用Dapper也是不行的，可以使用`OracleDynamicParameters`这个对象，实测更新可以成功，插入不行；
类似下面的操作：
![image](https://user-images.githubusercontent.com/19462884/139381311-ded21417-29b3-4972-915a-b8b54a56619f.png)
